SpkProfileMatching/app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from app.config import setting

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^karyawan/', include('management.karyawan.urls', namespace='karyawan')),
    url(r'^kecerdasan/', include('management.kecerdasan.urls', namespace='kecerdasan')),
    url(r'^masakerja/', include('management.masakerja.urls', namespace='masakerja')),
    url(r'^pendidikanterakhir/', include('management.pendidikanterakhir.urls', namespace='pendidikanterakhir')),
    url(r'^prilaku/', include('management.prilaku.urls', namespace='prilaku')),
    url(r'^sikapkerja/', include('management.sikapkerja.urls', namespace='sikapkerja')),
    url(r'^perangkingan/', include('management.perangkingan.urls', namespace='perangkingan')),





]

SpkProfileMatching/management/prilaku/urls.py
from django.conf.urls import url
from management.prilaku import views


urlpatterns = [
    url (r'^$', views.ListPrilakuView.as_view(), name='view'),
    url (r'^cf$', views.ListCfView.as_view(), name='cf'),
    url (r'^sf$', views.ListSfView.as_view(), name='sf'),
    url (r'^totalcf$', views.ListNiCfView.as_view(), name='totalcf'),
    url (r'^totalsf$', views.ListNiSfView.as_view(), name='totalsf'),
    url (r'^total$', views.ListTotalView.as_view(), name='total'),

]

SpkProfileMatching/templates/layout/dashboard/css.html
{% load staticfiles %}
<!-- komponen css -->
<link rel="stylesheet" href="{% static 'components/bootstrap/dist/css/bootstrap.min.css' %}">

<link rel="stylesheet" href="{% static 'components/font-awesome/css/font-awesome.min.css' %}">

<link rel="stylesheet" href="{% static 'components/admin-lte/plugins/jvectormap/jquery-jvectormap-1.2.2.css' %}">

<link rel="stylesheet" href="{% static 'components/admin-lte/dist/css/AdminLTE.css' %}">

<link rel="stylesheet" href="{% static 'components/admin-lte/dist/css/skins/_all-skins.min.css' %}">

<link rel="stylesheet" href="{% static 'components/datatables.net-bs/css/dataTables.bootstrap.css' %}">

SpkProfileMatching/templates/layout/dashboard/footer.html
<footer class="main-footer">
    <div class="pull-right hidden-xs">
    </div>
    <strong>Copyright © 2018-2019 <a href="#">Adhitya Nugraha</a>.</strong> Semoga bermanfaat
</footer>

SpkProfileMatching/templates/layout/dashboard/head.html
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>Document</title>

{% include 'layout/dashboard/css.html' %}
{% include 'layout/dashboard/js.html' %}

SpkProfileMatching/templates/layout/dashboard/header.html
<header class="main-header">
        <!-- Logo -->
        <a href="../../index2.html" class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini"><b>S</b>PK</span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg"><b><i><marquee>Sistem Pendukung Keputusan</marquee></i></b></span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
    
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <li class="dropdown user user-menu">
              </li>
              <!-- Control Sidebar Toggle Button -->
              <li>
              </li>
            </ul>
          </div>
        </nav>
      </header>

SpkProfileMatching/templates/layout/dashboard/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    {% include 'layout/dashboard/head.html' %}
</head>
<body class="hold-transition skin-blue sidebar-mini">
    {% include 'layout/dashboard/header.html' %}
    {% include 'layout/dashboard/sidebar.html' %}    
    {% block content %} {% endblock %}
    {% include 'layout/dashboard/footer.html' %}    
</body>
</html>

SpkProfileMatching/templates/layout/dashboard/js.html
{% load staticfiles %}
<!-- komponen js -->
<script src="{% static 'components/jquery/dist/jquery.js' %}"></script>
<script src="{% static 'components/jquery-ui/jquery-ui.js' %}"></script>

<script src="{% static 'components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<script src="{% static 'components/jquery-slimscroll/jquery.slimscroll.js' %}"></script>

<script src="{% static 'components/admin-lte/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js' %}"></script>
<script src="{% static 'components/admin-lte/plugins/jvectormap/jquery-jvectormap-world-mill-en.js' %}"></script>

<script src="{% static 'components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>

<script src="{% static 'components/admin-lte/dist/js/adminlte.js' %}"></script>
<script src="{% static 'components/admin-lte/dist/js/demo.js'%}"></script>

SpkProfileMatching/templates/layout/dashboard/sidebar.html
{% load staticfiles %}
<aside class="main-sidebar">
<!-- sidebar: style can be found in sidebar.less -->
<section class="sidebar" style="height: auto;">
    <!-- Sidebar user panel -->

    <!-- search form -->

    <!-- /.search form -->
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu tree" data-widget="tree">
        <li class="header" align="center">MAIN NAVIGATION</li>
        <li>
            <a href="{% url 'admin:index' %}">
                <i class="fa fa-user"></i> Admin Site</a>
        </li>
        <li class="header"></li>
        <li>
            <a href="{% url 'karyawan:view' %}">
                <i class="fa fa-user"></i> karyawan</a>
        </li>
        <li class="header"></li>
        <li class="treeview menu-open">
            <a href="#">
                <i class="fa fa-database" aria-hidden="true"></i><span>Kecerdasan</span>
                <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
            </span>
            </a>
            <ul class="treeview-menu" style="display: block;">
                <li><a href="{% url 'kecerdasan:view' %}"><i class="fa fa-circle-o"></i> Nilai Kecerdasan</a></li>
                <li><a href="{% url 'kecerdasan:cf' %}"><i class="fa fa-circle-o"></i> Nilai Core Factor </a></li>
                <li><a href="{% url 'kecerdasan:sf' %}"><i class="fa fa-circle-o"></i> Nilai Secondary Factor </a></li>
                <li><a href="{% url 'kecerdasan:totalcf' %}"><i class="fa fa-circle-o"></i> Hasil CF </a></li>
                <li><a href="{% url 'kecerdasan:totalsf' %}"><i class="fa fa-circle-o"></i> Hasil SF </a></li>
                <li><a href="{% url 'kecerdasan:total' %}"><i class="fa fa-circle-o"></i> Nilai Total </a></li>

                
            </ul>
        </li>
        <li class="treeview menu-open">
            <a href="#">
                <i class="fa fa-database" aria-hidden="true"></i><span>Masa Kerja</span>
                <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
            </span>
            </a>
            <ul class="treeview-menu" style="display: block;">
                
                <li><a href="{% url 'masakerja:view' %}"><i class="fa fa-circle-o"></i> Nilai Masa Kerja </a></li>
                <li><a href="{% url 'masakerja:cf' %}"><i class="fa fa-circle-o"></i> Nilai Core Factor </a></li>
                <li><a href="{% url 'masakerja:sf' %}"><i class="fa fa-circle-o"></i> Nilai Secondary Factor </a></li>
                <li><a href="{% url 'masakerja:totalcf' %}"><i class="fa fa-circle-o"></i> Hasil CF </a></li>
                <li><a href="{% url 'masakerja:totalsf' %}"><i class="fa fa-circle-o"></i> Hasil SF </a></li>
                <li><a href="{% url 'masakerja:total' %}"><i class="fa fa-circle-o"></i> Nilai Total </a></li>


            </ul>
        </li>
        <li class="treeview menu-open">
                <a href="#">
                    <i class="fa fa-database" aria-hidden="true"></i><span>Pendidikan Terakhir</span>
                    <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                </span>
                </a>
                <ul class="treeview-menu" style="display: block;">
                    
                    <li><a href="{% url 'pendidikanterakhir:view' %}"><i class="fa fa-circle-o"></i> Nilai Pendidikan Terakhir</a></li>
                    <li><a href="{% url 'pendidikanterakhir:cf' %}"><i class="fa fa-circle-o"></i> Nilai Core Factor </a></li>
                    <li><a href="{% url 'pendidikanterakhir:sf' %}"><i class="fa fa-circle-o"></i> Nilai Secondary Factor </a></li>
                    <li><a href="{% url 'pendidikanterakhir:totalcf' %}"><i class="fa fa-circle-o"></i> Hasil CF </a></li>
                    <li><a href="{% url 'pendidikanterakhir:totalsf' %}"><i class="fa fa-circle-o"></i> Hasil SF </a></li>
                    <li><a href="{% url 'pendidikanterakhir:total' %}"><i class="fa fa-circle-o"></i> Nilai Total </a></li>


                </ul>
            </li>
            <li class="treeview menu-open">
                    <a href="#">
                        <i class="fa fa-database" aria-hidden="true"></i><span>Prilaku</span>
                        <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                    </a>
                    <ul class="treeview-menu" style="display: block;">
                        
                        <li><a href="{% url 'prilaku:view' %}"><i class="fa fa-circle-o"></i> Nilai Prilaku</a></li>
                        <li><a href="{% url 'prilaku:cf' %}"><i class="fa fa-circle-o"></i> Nilai Core Factor </a></li>
                        <li><a href="{% url 'prilaku:sf' %}"><i class="fa fa-circle-o"></i> Nilai Secondary Factor </a></li>
                        <li><a href="{% url 'prilaku:totalcf' %}"><i class="fa fa-circle-o"></i> Hasil CF </a></li>
                        <li><a href="{% url 'prilaku:totalsf' %}"><i class="fa fa-circle-o"></i> Hasil SF </a></li>
                        <li><a href="{% url 'prilaku:total' %}"><i class="fa fa-circle-o"></i> Nilai Total </a></li>
    
    
                    </ul>
                </li>

                <li class="treeview menu-open">
                        <a href="#">
                            <i class="fa fa-database" aria-hidden="true"></i><span>Sikap Kerja</span>
                            <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                        </a>
                        <ul class="treeview-menu" style="display: block;">
                            
                            <li><a href="{% url 'sikapkerja:view' %}"><i class="fa fa-circle-o"></i> Nilai Sikap Kerja</a></li>
                            <li><a href="{% url 'sikapkerja:cf' %}"><i class="fa fa-circle-o"></i> Nilai Core Factor </a></li>
                            <li><a href="{% url 'sikapkerja:sf' %}"><i class="fa fa-circle-o"></i> Nilai Secondary Factor </a></li>
                            <li><a href="{% url 'sikapkerja:totalcf' %}"><i class="fa fa-circle-o"></i> Hasil CF </a></li>
                            <li><a href="{% url 'sikapkerja:totalsf' %}"><i class="fa fa-circle-o"></i> Hasil SF </a></li>
                            <li><a href="{% url 'sikapkerja:total' %}"><i class="fa fa-circle-o"></i> Nilai Total </a></li>
        
        
                        </ul>
                    </li>
                    <li class="treeview menu-open">
                        <a href="#">
                            <i class="fa fa-database" aria-hidden="true"></i><span>Rangking</span>
                            <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                        </a>
                        <ul class="treeview-menu" style="display: block;">
                            <li><a href="{% url 'perangkingan:view' %}"><i class="fa fa-circle-o"></i> Hasil Rangking</a></li>
                            
                        </ul>
                    </li>
        <li class="header"></li>
</section>
<!-- /.sidebar -->
</aside>