SpkProfileMatching/app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from app.config import setting

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^karyawan/', include('management.karyawan.urls', namespace='karyawan')),
    url(r'^kecerdasan/', include('management.kecerdasan.urls', namespace='kecerdasan')),
    url(r'^masakerja/', include('management.masakerja.urls', namespace='masakerja')),
    url(r'^pendidikanterakhir/', include('management.pendidikanterakhir.urls', namespace='pendidikanterakhir')),
    url(r'^prilaku/', include('management.prilaku.urls', namespace='prilaku')),
    url(r'^sikapkerja/', include('management.sikapkerja.urls', namespace='sikapkerja')),
    url(r'^perangkingan/', include('management.perangkingan.urls', namespace='perangkingan')),





]

SpkProfileMatching/management/perangkingan/urls.py
from django.conf.urls import url
from management.perangkingan import views


urlpatterns = [
    url (r'^$', views.ListTotalView.as_view(), name='view'),
    url (r'^report$', views.GeneratePDF.as_view(), name='report'),
    # url (r'^print$', views.some_view, name='print'),
]

SpkProfileMatching/management/perangkingan/models.py
from django.db import models

# Create your models here.

SpkProfileMatching/management/perangkingan/views.py
from django.shortcuts import render, redirect, get_list_or_404
from django.views.generic import View
from django.http import HttpResponse
from django.contrib import messages

from orm.models import Karyawan, Kecerdasan, MasaKerja, PendidikanTerakhir, Prilaku, SikapKerja 
import pandas as pd

from management.perangkingan import helpers

from reportlab.pdfgen import canvas
from django.template.loader import get_template


class ListTotalView(View):
    def get(self, request):
        template = 'perangkingan/index.html'
        krywn = Karyawan.objects.all()
        nl = helpers.total_rangking(krywn).as_matrix()
        data = {
            'nl' : nl,
        }
        return render(request, template, data)

class GeneratePDF(View):
    def get(self, request, *args, **kwargs):
        template = get_template('perangkingan/report.html')
        krywn = Karyawan.objects.all()
        nl = helpers.total_rangking(krywn).as_matrix()
        data ={
            'nl' : nl,
        }
        html = template.render(data)
        pdf = helpers.render_to_pdf('perangkingan/report.html', data)
        return HttpResponse(pdf, content_type='application/pdf')

SpkProfileMatching/management/perangkingan/templates/perangkingan/index.html
{% extends 'layout/dashboard/index.html' %} {% block content %}
<div class="content-wrapper">
    <section class="content-header">
        <h1>
           Hasil Nilai Perangkingan
            <small>Template</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i>Hasil Nilai Perangkingan</a></li>
            <li class="active">Template</li>
        </ol>
    </section>
    <section class="content">
        <div class="row">
            {% comment %} <div class="col-sm-4">
                {% include 'dosen/form.html' %}
            </div> {% endcomment %}

            <div class="col-sm-12">
                {% include 'perangkingan/table.html' %}
            </div>
        </div>
    </section>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('#example1').DataTable( {
            "lengthMenu": [[5, 10, 25, 50, -1], [5, 10, 25, 50,]]
        } );
    } );
</script>
{% endblock %}

SpkProfileMatching/management/perangkingan/templates/perangkingan/report.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <title>Title</title>
        <style type="text/css">
            body {
                font-weight: 200;
                font-size: 14px;
            }
            .header {
                font-size: 20px;
                font-weight: 100;
                text-align: center;
                color: #007cae;
            }
            .title {
                font-size: 22px;
                font-weight: 100;
               /* text-align: right;*/
               padding: 10px 20px 0px 20px;  
            }
            .title span {
                color: #007cae;
            }
            .details {
                padding: 10px 20px 0px 20px;
                text-align: left !important;
                /*margin-left: 40%;*/
            }
            .hrItem {
                border: none;
                height: 1px;
                /* Set the hr color */
                color: #333; /* old IE */
                background-color: #fff; /* Modern Browsers */
            }
        </style>
    </head>
    <body>
        <div class='wrapper'>
            <div class='header'>
                <p class='title'>Report Perangkingan </p>
            </div>
        <div>
            <table class="details" border="1">
                <thead>
                    <th>No</th>
                    <th>Nama</th>
                    <th>Rangking</th>
                </thead>
                <tbody>
                {% for c in nl %}
                    <tr>
                        <td align="center">{{forloop.counter}}</td>
                        <td>{{c.0}}</td>
                        <td>{{c.1}}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
    </div>
    </body>
</html>

SpkProfileMatching/management/perangkingan/templates/perangkingan/table.html
<div class="box">
        <div class="box-body">
            <div class="box-header">
                <h3 class="box-title">Nilai Rangking</h3>
                <div align="right">
                        <a href="{% url 'perangkingan:report' %}">
                           <button class="btn btn-info"><i class="fa fa-print"></i> Print</button>
                        </a>
                    </div>
            </div>
            <table id="example" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Nama</th>
                        <th>Hasil Rangking</th>
                    </tr>
                </thead>
                <tbody>
                    {% for c in nl %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{c.0}}</td>
                        <td>{{c.1}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
    </div>
        </div>
    </section>
</div>

<script type="text/javascript">
    $('#example').DataTable();
</script>